using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace PowerPOS
{
    /// <summary>
    /// Controller class for ItemAttributesMap
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ItemAttributesMapController
    {
        // Preload our schema..
        ItemAttributesMap thisSchemaLoad = new ItemAttributesMap();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ItemAttributesMapCollection FetchAll()
        {
            ItemAttributesMapCollection coll = new ItemAttributesMapCollection();
            Query qry = new Query(ItemAttributesMap.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ItemAttributesMapCollection FetchByID(object ItemAttributesMapID)
        {
            ItemAttributesMapCollection coll = new ItemAttributesMapCollection().Where("ItemAttributesMapID", ItemAttributesMapID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ItemAttributesMapCollection FetchByQuery(Query qry)
        {
            ItemAttributesMapCollection coll = new ItemAttributesMapCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ItemAttributesMapID)
        {
            return (ItemAttributesMap.Delete(ItemAttributesMapID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ItemAttributesMapID)
        {
            return (ItemAttributesMap.Destroy(ItemAttributesMapID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ItemAttributesMapID,string ItemNo,string AttributesGroupCode,string UserFld1,string UserFld2,string UserFld3,string UserFld4,string UserFld5,DateTime? CreatedOn,string CreatedBy,DateTime? ModifiedOn,string ModifiedBy,bool? Deleted)
	    {
		    ItemAttributesMap item = new ItemAttributesMap();
		    
            item.ItemAttributesMapID = ItemAttributesMapID;
            
            item.ItemNo = ItemNo;
            
            item.AttributesGroupCode = AttributesGroupCode;
            
            item.UserFld1 = UserFld1;
            
            item.UserFld2 = UserFld2;
            
            item.UserFld3 = UserFld3;
            
            item.UserFld4 = UserFld4;
            
            item.UserFld5 = UserFld5;
            
            item.CreatedOn = CreatedOn;
            
            item.CreatedBy = CreatedBy;
            
            item.ModifiedOn = ModifiedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.Deleted = Deleted;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string ItemAttributesMapID,string ItemNo,string AttributesGroupCode,string UserFld1,string UserFld2,string UserFld3,string UserFld4,string UserFld5,DateTime? CreatedOn,string CreatedBy,DateTime? ModifiedOn,string ModifiedBy,bool? Deleted)
	    {
		    ItemAttributesMap item = new ItemAttributesMap();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ItemAttributesMapID = ItemAttributesMapID;
				
			item.ItemNo = ItemNo;
				
			item.AttributesGroupCode = AttributesGroupCode;
				
			item.UserFld1 = UserFld1;
				
			item.UserFld2 = UserFld2;
				
			item.UserFld3 = UserFld3;
				
			item.UserFld4 = UserFld4;
				
			item.UserFld5 = UserFld5;
				
			item.CreatedOn = CreatedOn;
				
			item.CreatedBy = CreatedBy;
				
			item.ModifiedOn = ModifiedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.Deleted = Deleted;
				
	        item.Save(UserName);
	    }
    }
}
