<%@ Page Title="<%$Resources:dictionary, Edit Purchase Order%>" Language="C#" MasterPageFile="~/PowerPOSMst.master"
    AutoEventWireup="true" CodeBehind="EditPO.aspx.cs" Inherits="PowerWeb.Inventory.EditPO" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <ajax:ScriptManager ID="ScriptManager1" runat="server">
    </ajax:ScriptManager>
    <cc1:CalendarExtender ID="cldStartDate" runat="server" Animated="False" Format="dd MMM yyyy"
        PopupButtonID="ImageButton1" TargetControlID="txtPurchaseOrderDate">
    </cc1:CalendarExtender>
    <cc1:CalendarExtender ID="cldEndDate" runat="server" Animated="False" Format="dd MMM yyyy"
        PopupButtonID="ImageButton2" TargetControlID="txtPurchaseOrderDate">
    </cc1:CalendarExtender>
    <table width="600px">
        <tr>
            <td colspan="4" >
                <asp:Label ID="lblError" runat="server" Text=""></asp:Label>
                
            </td>
        </tr>
        <tr>
            <td colspan="4" class="searchHeader">
                <asp:Literal ID="SEARCHLbl" runat="server" Text="<%$Resources:dictionary, Purchase Order Info%>"></asp:Literal>
            </td>
        </tr>
        <tr>
            <td class="fieldname" style="width: 122px">
                <asp:Literal ID="Literal1" runat="server" Text="<%$Resources:dictionary, Purchase Order No%>"></asp:Literal>
            </td>
            <td colspan="3">
                <asp:TextBox ID="txtPurchaseOrderHdrRefNo" runat="server" Width="172px"></asp:TextBox>
        </tr>
        <tr>
            <td class="fieldname" style="width: 122px">
                <asp:Literal ID="Literal3" runat="server" Text="<%$Resources:dictionary, Purchase Order Date%>"></asp:Literal>
            </td>
            <td style="width: 180px">
                <asp:TextBox ID="txtPurchaseOrderDate" runat="server"></asp:TextBox>
                <asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="~/App_Themes/Default/image/Calendar_scheduleHS.png"
                    Visible="false" />
            </td>
        </tr>
        <tr>
            <td class="fieldname" style="width: 122px">
                <asp:Literal ID="Literal2" runat="server" Text="<%$Resources:dictionary, Supplier%>"></asp:Literal>
            </td>
            <td style="width: 180px">
                <asp:DropDownList ID="cbSupplier" runat="server" Enabled="false">
                </asp:DropDownList>
        </tr>
        <tr>
            <td class="fieldname" style="width: 122px">
                <asp:Literal ID="Literal4" runat="server" Text="<%$Resources:dictionary, GST%>"></asp:Literal>
            </td>
            <td style="width: 180px">
                <asp:DropDownList ID="cbGST" runat="server" Enabled="false">
                </asp:DropDownList>
        </tr>
        <tr>
            <td class="fieldname" style="width: 122px">
                <asp:CheckBox ID="cbShowPreviousSales" runat="server" AutoPostBack="true" Checked="true"
                    OnCheckedChanged="cbShowPreviousSales_OnCheckedChanged" Text="<%$Resources:dictionary,Show Previous Sales %>" />
            </td>
            <td style="width: 180px">
                <asp:TextBox ID="txtRangeOfDays" Text="7" runat="server" AutoPostBack="true" OnTextChanged="txtRangeOfDays_OnTextChanged"></asp:TextBox>&nbsp;<asp:Literal
                    ID="Literal5" runat="server">Days</asp:Literal>
            </td>
        </tr>
    </table>
    <table width="600px">
        <tr>
            <td>
                <asp:GridView ID="gvItem" runat="server" AutoGenerateColumns="False" SkinID="scaffold"
                    OnRowCommand="gvItem_RowCommand" Width="800px" AutoGenerateDeleteButton="False"
                    ShowFooter="true" OnRowDataBound="gvItem_RowDataBound">
                    <Columns>
                        <asp:TemplateField HeaderText="<%$Resources:dictionary, Delete%>" ItemStyle-Width="100px"
                            HeaderStyle-Width="100px">
                            <ItemStyle HorizontalAlign="center" VerticalAlign="Middle" />
                            <ItemTemplate>
                                <asp:Button ID="btnDelete" runat="server" class="classname" Text="<%$Resources:dictionary, Delete%>"
                                    CommandName="DeleteDetail" CommandArgument='<%# Eval("PurchaseOrderDetRefNo") %>' OnClientClick="return confirm('Are you sure you want to delete this item?')" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="ItemNo" HeaderText="<%$Resources:dictionary,Item No %>"
                            SortExpression="ItemNo" />
                        <asp:BoundField DataField="ItemName" HeaderText="<%$Resources:dictionary,Item Name %>" />
                        <asp:BoundField DataField="PackingQuantity" HeaderText="<%$Resources:dictionary,Current Quantity %>"
                            DataFormatString="{0:0.####}" />
                        <asp:BoundField DataField="PackingSizeName" HeaderText="<%$Resources:dictionary,Current UOM %>" />
                        <asp:BoundField DataField="Quantity" HeaderText="<%$Resources:dictionary,Quantity In Base UOM %>"
                            DataFormatString="{0:0.####}" />
                        <asp:BoundField DataField="UOM" HeaderText="<%$Resources:dictionary,Base UOM %>" />
                        <asp:TemplateField HeaderText="<%$Resources:dictionary,Enter Quantity %>">
                            <ItemTemplate>
                                <asp:TextBox ID="txtQuantity" runat="server" Text='<%# Bind("PackingQuantity", "{0:0.####}") %>'
                                    Width="50px" OnTextChanged="RecalculateAmount" AutoPostBack="true"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="PackingSizeCost" HeaderText="<%$Resources:dictionary, Current Cost Price%>" />
                        <asp:TemplateField HeaderText="<%$Resources:dictionary, Enter Cost Price%>">
                            <ItemTemplate>
                                <asp:TextBox ID="txtCostOfGoods" runat="server" Text='<%# Bind("PackingSizeCost") %>'
                                    Width="50px" OnTextChanged="RecalculateAmount" AutoPostBack="true"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="<%$Resources:dictionary, Amount%>">
                            <ItemTemplate>
                                <asp:Label ID="lblAmount" runat="server" Text='<%#String.Format("{0:0.####}", Eval("Amount")) %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="GST" HeaderText="<%$Resources:dictionary,GST %>" />
                        <asp:BoundField DataField="OnHand" HeaderText="<%$Resources:dictionary,On Hand %>" />
                        <asp:TemplateField HeaderText="<%$Resources:dictionary, %>Ref No" Visible="false">
                            <ItemTemplate>
                                <asp:Label ID="lblPurchaseOrderDetRefNo" runat="server" Text='<%# Eval("PurchaseOrderDetRefNo") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField ItemStyle-Width="100px">
                            <ItemTemplate>
                                <asp:Label ID="lblSalesPeriod1" runat="server" Text='<%#String.Format("{0:0.####}", Eval("SalesPeriod1")) %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField ItemStyle-Width="100px">
                            <ItemTemplate>
                                <asp:Label ID="lblSalesPeriod2" runat="server" Text='<%#String.Format("{0:0.####}", Eval("SalesPeriod2")) %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField ItemStyle-Width="100px">
                            <ItemTemplate>
                                <asp:Label ID="lblSalesPeriod3" runat="server" Text='<%#String.Format("{0:0.####}", Eval("SalesPeriod3")) %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                <br />
            </td>
        </tr>
    </table>
    <asp:Button ID="btnSave" runat="server" class="classname" Text="<%$Resources:dictionary, Save%>"
        OnClick="btnSave_Click" />
    <%--<asp:Button ID="btnCancel" runat="server" class="classname" Text="Cancel" />--%>
    <input type="button" runat="server" class="classname" value="<%$Resources:dictionary, Cancel%>"
        onclick="javascript:window.close();" />
</asp:Content>
