declare @statement Nvarchar(max)
set @statement = ''

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FnGetEveryDateBetween]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
BEGIN
	set @statement = @statement + N'CREATE FUNCTION [dbo].[FnGetEveryDateBetween] '
END
ELSE
BEGIN
	set @statement = @statement + N'ALTER FUNCTION [dbo].[FnGetEveryDateBetween] '	
END
set @statement = @statement + N'
(	
	@startDate datetime, 
	@endDate datetime
)
RETURNS TABLE 
AS
RETURN 
(
    SELECT CONVERT(date, a.[Date]) AS [Date], DATENAME(WEEKDAY, a.[Date]) AS [WeekDay]
    FROM ( 
        SELECT DATEADD(DAY, -(a.a + (10 * b.a) + (100 * c.a) + (1000 * d.a)), @endDate) AS [Date] 
        FROM (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS a 
        CROSS JOIN (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS b 
        CROSS JOIN (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS c 
        CROSS JOIN (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS d 
    ) a 
    WHERE a.[Date] BETWEEN @startDate AND @endDate 
)'

EXEC dbo.sp_executesql @statement