ALTER TABLE OrderDet
ALTER COLUMN Quantity DECIMAL(20,5) NULL

ALTER TABLE InventoryDet
ALTER COLUMN Quantity DECIMAL(20,5) NULL

ALTER TABLE InventoryDet
ALTER COLUMN RemainingQty DECIMAL(20,5) NULL

ALTER TABLE StockTake
ALTER COLUMN StockTakeQty DECIMAL(20,5) NULL

ALTER TABLE StockTake
ALTER COLUMN BalQtyAtEntry DECIMAL(20,5) NULL

ALTER TABLE StockTake
ALTER COLUMN AdjustmentQty DECIMAL(20,5) NULL

ALTER TABLE PurchaseOrderDet
ALTER COLUMN Quantity DECIMAL(20,5) NULL

ALTER TABLE PurchaseOrderDet
ALTER COLUMN RemainingQty DECIMAL(20,5) NULL