
ALTER VIEW [dbo].[ViewInventoryActivity]  AS  
SELECT     D.InventoryDetRefNo, 
		   D.ItemNo, 
		   D.Quantity, 
		   D.RemainingQty, 
		   D.Remark AS ItemRemark,                         
		   H.InvoiceNo, 
		   H.Supplier, 
		   H.Remark, 
		   H.InventoryDate, 
		   H.UserName,                         
		   H.InventoryHdrRefNo, 
		   V.ItemName, 
		   V.CategoryName, 
		   I.InventoryLocationName,                         
		   H.MovementType, 
		   D.CostOfGoods, 
		   D.StockInRefNo, 
		   I.InventoryLocationID,                         
		   D.IsDiscrepancy, 
		   R.ReasonName, 
		   D.FactoryPrice, 
		   D.GST,                         
		   H.StockOutReasonID, 
		   V.RetailPrice, 
		   V.FactoryPrice AS FactoryPriceUSD, 
		   V.ProductLine,                         
		   H.DepartmentID, 
		   V.Attributes1, 
		   V.Attributes2, 
		   V.Attributes3, 
		   V.Attributes4, 
		   V.Attributes5,                         
		   V.Attributes6, 
		   V.Attributes7, 
		   V.Attributes8, 
		   V.Remark AS Expr1, 
		   V.ProductionDate,                         
		   V.hasWarranty, 
		   V.IsDelivery, 
		   V.GSTRule, 
		   V.IsVitaMix, 
		   V.IsWaterFilter, 
		   V.IsYoung,                         
		   V.IsJuicePlus, 
		   V.IsCourse, 
		   V.CourseTypeID, 
		   V.IsServiceItem, 
		   V.search, 
		   V.DepartmentName,                         
		   V.ItemDepartmentId, 
		   V.Barcode, 
		   V.ItemDesc, 
		   V.MinimumPrice, 
		   V.IsInInventory, 
		   V.Brand,                         
		   V.IsNonDiscountable, 
		   V.Deleted, 
		   D.BalanceBefore, 
		   D.BalanceAfter, 
		   D.ExpiryDate  
FROM      dbo.InventoryHdr H 
LEFT JOIN dbo.InventoryDet D ON D.InventoryHdrRefNo = H.InventoryHdrRefNo 
LEFT JOIN dbo.InventoryLocation I ON I.InventoryLocationID = H.InventoryLocationID 
LEFT JOIN dbo.ViewItem V ON D.ItemNo = V.ItemNo 
LEFT JOIN dbo.InventoryStockOutReason R ON H.StockOutReasonID = R.ReasonID  

