IF EXISTS(SELECT * FROM sys.columns WHERE [name] = N'userfld1' AND [object_id] = OBJECT_ID(N'UserPrivilege'))
BEGIN
    ALTER TABLE UserPrivilege ALTER COLUMN userfld1 varchar(max) null
END

update UserPrivilege set userflag1 = 1 where PrivilegeName  in ('Set Privileges', 'Setting')

Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Personal Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Retail Sales Cash Analysis Summary Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Retail Sales Cash Analysis Detail Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Retail Collection Breakdown' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Daily Product Sales Analysis Report (Summary)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Daily Product Sales Analysis Detail Report(Detail)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Accounting Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Pre Order Summary' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Sales Summary Daily Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Stock On Hand Summary Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Profit And Loss Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Daily Profit/Loss Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales Report (With Profit)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Average Bill Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Outlet Daily Sales' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Outlet Category Sales' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Outlet Daily Category Sales' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Daily Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Daily Sales VS Manual Submission Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Missing Daily Sales' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Outlet Transaction Hourly Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Transaction Hourly Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales Report By Gender' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales Report By Outlet and Gender' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Outlet Sales Report By Gender' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Overall Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales Report Without Redeem' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Category Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Department Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Attributes Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Monthly Average Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales By Day Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales By Month Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Product Sales By Month Report - Quantity' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Collection Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Transaction Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Transaction Detail Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Transaction Detail Report (With Payment Type)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Transaction Detail Report (With Cost)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Transaction Discount Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Remark Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Void Transaction Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Pre Order Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Pre Accrual List Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'User Activity Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Cash Recording Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Million Integration Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'SMF Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Monthly Funding Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Campaign Promo Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Performance Log Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Performance Log Summary Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Customer Rating Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Aggregated Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Aging Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '01. EQUIPWEB-REPORTS' where PrivilegeName = 'Cash Out Collection Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '02. EQUIPWEB-COMMISSION' where PrivilegeName = 'Commission by Percentage Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '02. EQUIPWEB-COMMISSION' where PrivilegeName = 'Commission by Quantity Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '02. EQUIPWEB-COMMISSION' where PrivilegeName = 'New Commission Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Commission Report (Summary)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Commission Report (Detail)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Commission Report (Category Detail)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Commission Report (By Percentage)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Commission Report (Per Sales Person)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Commission Report (Quantity)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Person Performance Report (NEW)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Person Performance Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Person Profit Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Return(Deduction) Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Product Sales Report - By Sales Person' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Product Sales Report - By Assistant' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Detailed Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Assistant''s Sales Report By Day' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'Sales Person Report By Receipt' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '03. EQUIPWEB-SALES PERSON REPORT' where PrivilegeName = 'New Commission Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Balance Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Balance Report (With Cost)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Balance Report by Date' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Balance by Attributes' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Card Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Card Report (Detailed)' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Summary Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Product Pre Order Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Goods Receive Summary Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Goods Receive Detail Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Activity Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Transfer Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Out Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Take Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Variance Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Stock Take Item Miss-out Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Unadjusted Stock Take Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Item Trace Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Undeducted Sales Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Delivery List' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Purchase Order Approval' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Low Quantity Item Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Approve Stock Take' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Supplier List Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Item Supplier Map Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '04. EQUIPWEB-INVENTORY REPORT' where PrivilegeName = 'Roll Forward Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '05. EQUIPWEB-SUPPLIER' where PrivilegeName = 'Purchase Order Approval' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '05. EQUIPWEB-SUPPLIER' where PrivilegeName = 'Item Supplier and Cost Price Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '05. EQUIPWEB-SUPPLIER' where PrivilegeName = 'Item Supplier Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '05. EQUIPWEB-SUPPLIER' where PrivilegeName = 'Supplier Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '05. EQUIPWEB-SUPPLIER' where PrivilegeName = 'Currency Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'New Product Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Product Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Category Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Item Department Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Item Attributes Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'View Promo' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Item Group Promo' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Setup Product Promotion' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Alternate Item Barcode Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Currency Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Item Cost Price Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Item Quantity Warning Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Deleted Product List' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Add New Item' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Deleted Product Stock Balance' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '06. EQUIPWEB-PRODUCT' where PrivilegeName = 'Shelf Tag Printing' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '07. EQUIPWEB-DELIVERY' where PrivilegeName = 'Update Delivery Details' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '07. EQUIPWEB-DELIVERY' where PrivilegeName = 'Print Delivery Order' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '07. EQUIPWEB-DELIVERY' where PrivilegeName = 'Update Balance Payment' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'New Membership' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Membership Group Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Membership Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Membership Product Sales Repor' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Customer Purchase Detail Summary' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Customer Purchase Summary Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Customer Purchase By Category Repor' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'View Members Points' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'View Membership Package' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Membership Attendance Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Customer Attendance Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Outstanding Installment Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Package Utilization Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Membership Unused Balance Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '08. EQUIPWEB-MEMBERSHIP' where PrivilegeName = 'Customer Purchase By Category Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '09. EQUIPWEB-APPOINTMENT' where PrivilegeName = 'Daily Appointment View' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '09. EQUIPWEB-APPOINTMENT' where PrivilegeName = 'Resource Group Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '09. EQUIPWEB-APPOINTMENT' where PrivilegeName = 'Resource Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '09. EQUIPWEB-APPOINTMENT' where PrivilegeName = 'Create Appointment' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '09. EQUIPWEB-APPOINTMENT' where PrivilegeName = 'View Appointment' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Outlet Group' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Outlet Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Point Of Sale Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Tenant Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Mall Integration Validator' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Tenant History' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'User Management' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Group Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Set Privileges' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Assign Privileges' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Project Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Setup Inventory Location' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Setup Stock Out Reason' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'GST Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Line Info Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Hot Keys Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Freeze POS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Setting' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Item Importer' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Low Qty Importer' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Generate Salesman App JSON File' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Ward Top Up Importer' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Stock Take Importer' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'View DB Log' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Access Log Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'POS Exception Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Audit Log Report' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Discount Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Voucher Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Promo By Item' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Promo By Group' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Guest Book Compulsory Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'Customer Rating Settings' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '10. EQUIPWEB-SYSTEM SETUP' where PrivilegeName = 'SAP Customer Code Setup' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'CASH RECORDING' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'SALES INVOICE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'CREDIT INVOICE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'CHECK OUT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'VIEW SALES' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'FORMAL INVOICE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'SALES DETAILS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'SALES BY PRODUCT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'SALES BY SALES PERSON' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'PRODUCT SALES BY SALES PERSON' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'SALES PERSON PERFORMANCE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'QUOTATION' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'DAILY SALES' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'DELIVERY ORDER' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'VIEW DELIVERY' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'APPOINTMENT MANAGER' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Z2 CLOSING' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'CLOSING REPORT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'MONTHLY APPOINTMENT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'ROOM STATUS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Deduct Point' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Check Out' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Void Bill' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Select Sales Person' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Give Discount' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Give Refund' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Give Manual Discount' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Accept Close Counter' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'Give FOC' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '11. POS-SALES' where PrivilegeName = 'VIEW QUOTATIONS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'PRODUCT LIST' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'MEMBERS LIST' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'VOUCHERS LIST' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'MEMBERS ATTENDANCE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'MEMBERS GUESTBOOK' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'NEW SIGN UPS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'USER LIST' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'UPLOAD ITEM PHOTOS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '12. POS-LISTING' where PrivilegeName = 'OUTSTANDING INSTALLMENT REPORT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'GOODS RECEIVE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK ON HAND' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'ADJUST STOCK TAKE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'VIEW ACTIVITY BY ITEM' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK ISSUE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK SUMMARY REPORT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK ADJUSTMENT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK TAKE REPORT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK CARD' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK TAKE' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'VIEW ACTIVITY' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'STOCK TRANSFER' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'IMPORT INVENTORY' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'PURCHASE ORDER' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'VIEW PURCHASE ORDER' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'Load Saved' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '13. POS-INVENTORY' where PrivilegeName = 'BARCODE PRINTER' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'SYNC DATA' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'POS SETUP' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'BUTTON SETUP' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'EXCHANGE RATE SETUP' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'IMPORT POINTS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'EXTRA CHARGE SETUP' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'PAYMENT TYPE SETUP' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'VIEW SYNC LOG' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'FREEZE POS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'PRIVILEGE SETUP' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'SUPPORT' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'CONNECT NOW' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'MAGENTO SYNC' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'ALL INFO' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'FEATURES' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '14. POS-SETUP' where PrivilegeName = 'UpdatePOS' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '15. KIOSK' where PrivilegeName = 'Kiosk Setting Page' and ISNULL(userfld1,'') = ''
Update UserPrivilege set userfld1 = '15. KIOSK' where PrivilegeName = 'Kiosk Staff Function' and ISNULL(userfld1,'') = ''

update UserPrivilege set userflag1 = 1 where ISNULL(userfld1,'') = '' 

update UserPrivilege set userflag2 = 1, userflag3 = 1, userflag4 = 1, userint2 = 1, ModifiedOn = GETDATE()
where isnull(userint2, 0) = 0





