IF (SELECT  CHARACTER_MAXIMUM_LENGTH
	FROM	INFORMATION_SCHEMA.COLUMNS
	WHERE	TABLE_SCHEMA='dbo'
			AND COLUMN_NAME = 'Userfld6'
			AND TABLE_NAME = 'StockTake') <> -1 
BEGIN
	ALTER TABLE StockTake ALTER COLUMN Userfld6 NVARCHAR(MAX)
	ALTER TABLE StockTake ALTER COLUMN Userfld7 NVARCHAR(MAX)
	ALTER TABLE StockTake ALTER COLUMN Userfld8 NVARCHAR(MAX)
	ALTER TABLE StockTake ALTER COLUMN Userfld9 NVARCHAR(MAX)
	ALTER TABLE StockTake ALTER COLUMN Userfld10 NVARCHAR(MAX)
END