IF (SELECT COUNT(*) FROM sys.indexes WHERE name='IX_OrderHdr_DataIndex' AND object_id = OBJECT_ID('dbo.OrderHdr')) = 0 BEGIN
	CREATE NONCLUSTERED INDEX [IX_OrderHdr_DataIndex] ON [dbo].[OrderHdr]
	(
		[DataIndex] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
IF (SELECT COUNT(*) FROM sys.indexes WHERE name='IX_OrderDet_DataIndex' AND object_id = OBJECT_ID('dbo.OrderDet')) = 0 BEGIN
	CREATE NONCLUSTERED INDEX [IX_OrderDet_DataIndex] ON [dbo].[OrderDet]
	(
		[DataIndex] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
IF (SELECT COUNT(*) FROM sys.indexes WHERE name='IX_ReceiptDet_DataIndex' AND object_id = OBJECT_ID('dbo.ReceiptDet')) = 0 BEGIN
	CREATE NONCLUSTERED INDEX [IX_ReceiptDet_DataIndex] ON [dbo].[ReceiptDet]
	(
		[DataIndex] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END